receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels: {}
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:

processors:
  batch:

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - jaeger
    metrics:
      receivers: [otlp]
      processors:
        - batch
      exporters:
        - prometheus
        - logging